// ============================================
// SERVORA ERP — Payroll Types
// ============================================

import { Timestamp } from "firebase/firestore";

export interface AllowanceItem {
  name: string;
  amount: number;
  taxable: boolean;
}

export type PayrollStatus = "DRAFT" | "GENERATED" | "PAID";

// ✅ Snapshot — historical accuracy guaranteed
export interface PayrollSnapshot {
  basicSalary: number;
  hourlyRate: number;
  overtimeRate: number;
  holidayRate: number;
  nightRate: number;
  taxRate: number;
  ssRate: number;
}

// ✅ Attendance — reusable interface
export interface PayrollAttendance {
  workingDays: number;
  totalHours: number;
  overtimeHours: number;
  nightHours: number;
  holidayDays: number;
  holidayHours: number;
  absentDays: number;
  sickDays: number;
  vacationDays: number;
  trainingHours: number;
}

// Monthly attendance from Schedule
export interface MonthlyAttendance extends PayrollAttendance {
  employeeNo: string;
  employeeName: string;
  position: string;
  employeeSnapshot: PayrollSnapshot;
  // ✅ Restaurant settings at time of scheduling
  restaurantPayrollDays?: number;
  allowances: AllowanceItem[];
}

// Calculation result
export interface PayrollCalculation {
  earnedBasic: number;
  overtimePay: number;
  holidayPay: number;
  nightPay: number;
  taxableAllowances: number;
  nonTaxableAllowances: number;
  grossSalary: number;
  taxAmount: number;
  socialSecurityAmount: number;
  netSalary: number;
}

// Firestore payroll document
export interface PayrollDocument {
  id: string;
  employeeNo: string;
  employeeName: string;
  position: string;
  month: string;
  snapshot: PayrollSnapshot;
  attendance: PayrollAttendance;
  allowances: AllowanceItem[];
  calculation: PayrollCalculation;
  otherDeductions: number;
  payrollStatus: PayrollStatus;
  locked: boolean;
  autoGenerated: boolean;
  fromSchedule: boolean;
  restaurantId: string;
  userId: string;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
}