// ============================================
// SERVORA ERP — Payroll Service v3
// ✅ Snapshot fields added
// ✅ overtimeRate/holidayRate/nightRate from DB
// ✅ Per-day OT calculation fixed
// ✅ Lock after generate
// ✅ Batch writes
// ============================================

import {
  collection, getDocs, query,
  where, serverTimestamp, writeBatch, doc,
} from "firebase/firestore";
import { db, auth } from "../firebase";

// ── Types ────────────────────────────────────
export interface AllowanceItem {
  name: string;
  amount: number;
  taxable: boolean;
}

export interface PayrollInput {
  employeeNo: string;
  employeeName: string;
  position: string;
  nif: string;
  address: string;
  month: string;
  // ✅ Snapshots — historical record never changes
  basicSalarySnapshot: number;
  overtimeRateSnapshot: number;
  holidayRateSnapshot: number;
  nightRateSnapshot: number;
  taxRateSnapshot: number;
  ssRateSnapshot: number;
  // Attendance
  workingDays: number;
  totalDays: number;
  overtimeHours: number;
  nightHours: number;
  holidayDays: number;
  holidayHours: number;
  allowances: AllowanceItem[];
  otherDeductions: number;
  autoGenerated?: boolean;
  fromSchedule?: boolean;
}

export interface PayrollCalculation {
  earnedBasic: number;
  overtimePay: number;
  holidayPay: number;
  nightPay: number;
  taxableAllowances: number;
  nonTaxableAllowances: number;
  grossSalary: number;
  taxAmount: number;
  socialSecurityAmount: number;
  netSalary: number;
}

export interface MonthlyAttendance {
  employeeNo: string;
  employeeName: string;
  position: string;
  totalHours: number;
  overtimeHours: number;
  nightHours: number;
  workingDays: number;
  absentDays: number;
  holidayDays: number;
  holidayHours: number;
  sickDays: number;
  vacationDays: number;
}

// ── Calculation Engine ────────────────────────
export function calculatePayroll(input: PayrollInput): PayrollCalculation {
  const {
    basicSalarySnapshot: basicSalary,
    overtimeRateSnapshot: overtimeRate,
    holidayRateSnapshot: holidayRate,
    nightRateSnapshot: nightRate,
    taxRateSnapshot: taxRate,
    ssRateSnapshot: ssRate,
    workingDays, totalDays,
    overtimeHours, nightHours,
    holidayDays, holidayHours,
    allowances, otherDeductions,
  } = input;

  const safeDays   = totalDays > 0 ? totalDays : 30;
  const dailyRate  = basicSalary / safeDays;
  const hourlyRate = basicSalary / 160;
  const r = (n: number) => Math.round(n * 100) / 100;

  const earnedBasic          = r(dailyRate * workingDays);
  const overtimePay          = r(overtimeHours * hourlyRate * overtimeRate);
  const holidayPay           = r(holidayHours * hourlyRate * holidayRate);
  const nightPay             = r(nightHours * hourlyRate * (nightRate - 1));
  const taxableAllowances    = r(allowances.filter((a) => a.taxable).reduce((s, a) => s + a.amount, 0));
  const nonTaxableAllowances = r(allowances.filter((a) => !a.taxable).reduce((s, a) => s + a.amount, 0));
  const grossSalary          = r(earnedBasic + overtimePay + holidayPay + nightPay + taxableAllowances + nonTaxableAllowances);
  const taxableBase          = earnedBasic + overtimePay + holidayPay + nightPay + taxableAllowances;
  const taxAmount            = r((taxableBase * taxRate) / 100);
  const socialSecurityAmount = r((grossSalary * ssRate) / 100);
  const netSalary            = r(grossSalary - taxAmount - socialSecurityAmount - otherDeductions);

  return {
    earnedBasic, overtimePay, holidayPay, nightPay,
    taxableAllowances, nonTaxableAllowances,
    grossSalary, taxAmount, socialSecurityAmount, netSalary,
  };
}

// ── Get monthly attendance from Schedule ──────
export async function getMonthlyAttendance(
  restaurantId: string,
  year: number,
  month: number
): Promise<MonthlyAttendance[]> {
  // Get all weeks that overlap with this month
  const weeks = new Set<string>();
  const startMonday = new Date(year, month, 1);
  const dow = startMonday.getDay();
  startMonday.setDate(startMonday.getDate() - (dow === 0 ? 6 : dow - 1));
  const endDate = new Date(year, month + 1, 0);
  const cursor = new Date(startMonday);
  while (cursor <= endDate) {
    weeks.add(cursor.toISOString().split("T")[0]);
    cursor.setDate(cursor.getDate() + 7);
  }

  // ✅ Parallel reads
  const weekSnaps = await Promise.all(
    Array.from(weeks).map((week) =>
      getDocs(query(
        collection(db, "restaurants", restaurantId, "schedules"),
        where("weekStart", "==", week)
      ))
    )
  );

  const empMap: Record<string, MonthlyAttendance> = {};

  weekSnaps.forEach((snap) => {
    snap.docs.forEach((docSnap) => {
      const s = docSnap.data() as any;
      if (!empMap[s.employeeNo]) {
        empMap[s.employeeNo] = {
          employeeNo:   s.employeeNo,
          employeeName: s.employeeName,
          position:     s.position ?? s.category,
          totalHours:   0,
          overtimeHours: 0,
          nightHours:   0,
          workingDays:  0,
          absentDays:   0,
          holidayDays:  0,
          holidayHours: 0,
          sickDays:     0,
          vacationDays: 0,
        };
      }

      // Only count days that fall in this month
      Object.entries(s.days || {}).forEach(([dateStr, dayData]: [string, any]) => {
        const d = new Date(dateStr);
        if (d.getMonth() !== month || d.getFullYear() !== year) return;

        const emp = empMap[s.employeeNo];
        switch (dayData.status) {
          case "WORK":
            emp.totalHours   += dayData.hours || 0;
            emp.nightHours   += dayData.nightHours || 0;
            emp.workingDays  += 1;
            // ✅ Per-day OT fix
            if ((dayData.hours || 0) > 8) {
              emp.overtimeHours += (dayData.hours - 8);
            }
            break;
          case "ABSENT":   emp.absentDays++;   break;
          case "HOLIDAY":  emp.holidayDays++;  emp.holidayHours += 8; break;
          case "SICK":     emp.sickDays++;     break;
          case "VACATION": emp.vacationDays++; break;
        }
      });
    });
  });

  return Object.values(empMap);
}

// ── Auto generate monthly payroll ────────────
export async function generateMonthlyPayroll(
  restaurantId: string,
  year: number,
  month: number,
  monthStr: string
): Promise<{ created: number; skipped: number }> {

  const attendance = await getMonthlyAttendance(restaurantId, year, month);
  if (attendance.length === 0) return { created: 0, skipped: 0 };

  // Check existing payrolls
  const existingSnap = await getDocs(query(
    collection(db, "restaurants", restaurantId, "payroll"),
    where("month", "==", monthStr)
  ));
  const existingNos = new Set(existingSnap.docs.map((d) => d.data().employeeNo as string));

  const toCreate = attendance.filter((emp) => !existingNos.has(emp.employeeNo));
  const skipped  = attendance.length - toCreate.length;
  if (toCreate.length === 0) return { created: 0, skipped };

  // ✅ Fetch employee master DB for snapshots
  const empNos = toCreate.map((e) => e.employeeNo);
  const CHUNK  = 30;
  const masterMap: Record<string, any> = {};
  for (let i = 0; i < empNos.length; i += CHUNK) {
    const empSnap = await getDocs(query(
      collection(db, "restaurants", restaurantId, "employees"),
      where("employeeNo", "in", empNos.slice(i, i + CHUNK))
    ));
    empSnap.docs.forEach((d) => {
      const emp = d.data();
      masterMap[emp.employeeNo] = emp;
    });
  }

  // ✅ Batch writes
  const BATCH_LIMIT = 400;
  let created = 0;
  const safeMonth = monthStr.replace(/[^a-zA-Z0-9-]/g, "_");

  for (let i = 0; i < toCreate.length; i += BATCH_LIMIT) {
    const chunk = toCreate.slice(i, i + BATCH_LIMIT);
    const batch = writeBatch(db);

    chunk.forEach((emp) => {
      const master = masterMap[emp.employeeNo];

      // ✅ All rates from Employee DB as snapshots
      const input: PayrollInput = {
        employeeNo:   emp.employeeNo,
        employeeName: emp.employeeName,
        position:     master?.position ?? emp.position,
        nif:          master?.nif ?? "",
        address:      master?.address ?? "",
        month:        monthStr,

        // ✅ Snapshots — historical record guaranteed
        basicSalarySnapshot:  master?.basicSalary    ?? 0,
        overtimeRateSnapshot: master?.overtimeRate   ?? 1.5,
        holidayRateSnapshot:  master?.holidayRate    ?? 2.0,
        nightRateSnapshot:    master?.nightRate      ?? 1.25,
        taxRateSnapshot:      master?.taxRate        ?? 11,
        ssRateSnapshot:       master?.ssRate         ?? 11,

        // Attendance from schedule
        workingDays:   emp.workingDays,
        totalDays:     30,
        overtimeHours: emp.overtimeHours,
        nightHours:    emp.nightHours,
        holidayDays:   emp.holidayDays,
        holidayHours:  emp.holidayHours,
        allowances:    master?.allowances ?? [],
        otherDeductions: 0,
        autoGenerated: true,
        fromSchedule:  true,
      };

      const calc = calculatePayroll(input);

      const docId     = `${emp.employeeNo}_${safeMonth}`;
      const newDocRef = doc(db, "restaurants", restaurantId, "payroll", docId);

      batch.set(newDocRef, {
        ...input,
        ...calc,
        locked: true,   // ✅ Lock after generate
        restaurantId,
        userId:    auth.currentUser?.uid ?? "",
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      created++;
    });

    await batch.commit();
  }

  return { created, skipped };
}