// ============================================
// SERVORA ERP — Payroll Service v2
// Batch reads + Batch writes + Employee DB
// N+1 fixed + Deterministic IDs
// ============================================

import {
  collection, getDocs, query,
  where, serverTimestamp, writeBatch, doc,
} from "firebase/firestore";
import { db, auth } from "../firebase";

// ── Types ────────────────────────────────────
export interface AllowanceItem {
  name: string;
  amount: number;
  taxable: boolean;
}

export interface EmployeeRecord {
  id: string;
  employeeNo: string;
  employeeName: string;
  position: string;
  nif: string;
  address: string;
  basicSalary: number;
  taxRate: number;
  socialSecurityRate: number;
  contractType: "FULL_TIME" | "PART_TIME" | "TEMPORARY";
  active: boolean;
  restaurantId: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface PayrollInput {
  employeeNo: string;
  employeeName: string;
  position: string;
  nif: string;
  address: string;
  month: string;
  basicSalary: number;
  workingDays: number;
  totalDays: number;
  overtimeHours: number;
  overtimeRate: number;
  holidayDays: number;
  holidayRate: number;
  allowances: AllowanceItem[];
  taxRate: number;
  socialSecurityRate: number;
  otherDeductions: number;
  autoGenerated?: boolean;
  fromSchedule?: boolean;
}

export interface PayrollCalculation {
  earnedBasic: number;
  overtimePay: number;
  holidayPay: number;
  taxableAllowances: number;
  nonTaxableAllowances: number;
  grossSalary: number;
  taxAmount: number;
  socialSecurityAmount: number;
  netSalary: number;
}

export interface MonthlyAttendance {
  employeeNo: string;
  employeeName: string;
  category: string;
  basicSalary: number;
  taxRate: number;
  socialSecurityRate: number;
  totalHours: number;
  overtimeHours: number;
  workingDays: number;
  absentDays: number;
  holidayDays: number;
}

// ── Calculation Engine ────────────────────────
export function calculatePayroll(input: PayrollInput): PayrollCalculation {
  const {
    basicSalary, workingDays, totalDays,
    overtimeHours, overtimeRate,
    holidayDays, holidayRate,
    allowances, taxRate,
    socialSecurityRate, otherDeductions,
  } = input;

  const safeDays   = totalDays > 0 ? totalDays : 30;
  const dailyRate  = basicSalary / safeDays;
  const hourlyRate = basicSalary / (safeDays * 8);
  const r = (n: number) => Math.round(n * 100) / 100;

  const earnedBasic          = r(dailyRate * workingDays);
  const overtimePay          = r(overtimeHours * hourlyRate * overtimeRate);
  const holidayPay           = r(holidayDays * dailyRate * holidayRate);
  const taxableAllowances    = r(allowances.filter((a) => a.taxable).reduce((s, a) => s + a.amount, 0));
  const nonTaxableAllowances = r(allowances.filter((a) => !a.taxable).reduce((s, a) => s + a.amount, 0));
  const grossSalary          = r(earnedBasic + overtimePay + holidayPay + taxableAllowances + nonTaxableAllowances);
  const taxableBase          = earnedBasic + overtimePay + holidayPay + taxableAllowances;
  const taxAmount            = r((taxableBase * taxRate) / 100);
  const socialSecurityAmount = r((grossSalary * socialSecurityRate) / 100);
  const netSalary            = r(grossSalary - taxAmount - socialSecurityAmount - otherDeductions);

  return {
    earnedBasic, overtimePay, holidayPay,
    taxableAllowances, nonTaxableAllowances,
    grossSalary, taxAmount, socialSecurityAmount, netSalary,
  };
}

// ── Get monthly attendance ────────────────────
export async function getMonthlyAttendance(
  restaurantId: string,
  year: number,
  month: number
): Promise<MonthlyAttendance[]> {
  const weeks = new Set<string>();
  const startMonday = new Date(year, month, 1);
  const dow = startMonday.getDay();
  startMonday.setDate(startMonday.getDate() - (dow === 0 ? 6 : dow - 1));
  const endDate = new Date(year, month + 1, 0);
  const cursor = new Date(startMonday);
  while (cursor <= endDate) {
    weeks.add(cursor.toISOString().split("T")[0]);
    cursor.setDate(cursor.getDate() + 7);
  }

  // ✅ All weeks parallel
  const weekSnaps = await Promise.all(
    Array.from(weeks).map((week) =>
      getDocs(query(
        collection(db, "restaurants", restaurantId, "schedules"),
        where("weekStart", "==", week)
      ))
    )
  );

  const empMap: Record<string, MonthlyAttendance> = {};

  weekSnaps.forEach((snap) => {
    snap.docs.forEach((docSnap) => {
      const s = docSnap.data() as any;
      if (!empMap[s.employeeNo]) {
        empMap[s.employeeNo] = {
          employeeNo: s.employeeNo,
          employeeName: s.employeeName,
          category: s.category,
          basicSalary: s.basicSalary || 0,
          taxRate: s.taxRate || 11,
          socialSecurityRate: s.socialSecurityRate || 11,
          totalHours: 0,
          overtimeHours: 0,
          workingDays: 0,
          absentDays: 0,
          holidayDays: 0,
        };
      }
      Object.entries(s.days || {}).forEach(([dateStr, dayData]: [string, any]) => {
        const d = new Date(dateStr);
        if (d.getMonth() !== month || d.getFullYear() !== year) return;
        if (dayData.status === "WORK") {
          empMap[s.employeeNo].totalHours += dayData.hours || 0;
          empMap[s.employeeNo].workingDays += 1;
        } else if (dayData.status === "ABSENT") {
          empMap[s.employeeNo].absentDays += 1;
        } else if (dayData.status === "HOLIDAY") {
          empMap[s.employeeNo].holidayDays += 1;
        }
      });
    });
  });

  Object.values(empMap).forEach((emp) => {
    emp.overtimeHours = Math.max(0, emp.totalHours - emp.workingDays * 8);
  });

  return Object.values(empMap);
}

// ── Auto generate payroll ─────────────────────
export async function generateMonthlyPayroll(
  restaurantId: string,
  year: number,
  month: number,
  monthStr: string
): Promise<{ created: number; skipped: number }> {

  const attendance = await getMonthlyAttendance(restaurantId, year, month);
  if (attendance.length === 0) return { created: 0, skipped: 0 };

  // ✅ Single read — existing payroll
  const existingSnap = await getDocs(query(
    collection(db, "restaurants", restaurantId, "payroll"),
    where("month", "==", monthStr)
  ));
  const existingNos = new Set(
    existingSnap.docs.map((d) => d.data().employeeNo as string)
  );

  const toCreate = attendance.filter((emp) => !existingNos.has(emp.employeeNo));
  const skipped  = attendance.length - toCreate.length;
  if (toCreate.length === 0) return { created: 0, skipped };

  // ✅ Employee master DB — chunk read only needed employees
  const empNos = toCreate.map((e) => e.employeeNo);
  const CHUNK  = 30;
  const masterMap: Record<string, any> = {};
  for (let i = 0; i < empNos.length; i += CHUNK) {
    const empChunk = empNos.slice(i, i + CHUNK);
    const empSnap  = await getDocs(query(
      collection(db, "restaurants", restaurantId, "employees"),
      where("employeeNo", "in", empChunk)
    ));
    empSnap.docs.forEach((d: any) => {
      const emp = d.data();
      masterMap[emp.employeeNo] = emp;
    });
  }

  // ✅ writeBatch — max 400 per batch
  const BATCH_LIMIT = 400;
  let created    = 0;
  let batchIndex = 0;
  const safeMonth = monthStr.replace(/[^a-zA-Z0-9-]/g, "_");

  while (batchIndex < toCreate.length) {
    const chunk = toCreate.slice(batchIndex, batchIndex + BATCH_LIMIT);
    const batch = writeBatch(db);

    chunk.forEach((emp) => {
      const master      = masterMap[emp.employeeNo];
      const basicSalary = master?.basicSalary ?? emp.basicSalary;
      const taxRate     = master?.taxRate ?? emp.taxRate ?? 11;
      const ssRate      = master?.socialSecurityRate ?? emp.socialSecurityRate ?? 11;
      const position    = master?.position ?? emp.category;
      const nif         = master?.nif ?? "";
      const address     = master?.address ?? "";

      const input: PayrollInput = {
        employeeNo: emp.employeeNo,
        employeeName: emp.employeeName,
        position, nif, address,
        month: monthStr,
        basicSalary,
        workingDays: emp.workingDays,
        totalDays: 30,
        overtimeHours: emp.overtimeHours,
        overtimeRate: 1.5,
        holidayDays: emp.holidayDays,
        holidayRate: 2.0,
        allowances: master?.defaultAllowances ?? [],
        taxRate,
        socialSecurityRate: ssRate,
        otherDeductions: 0,
        autoGenerated: true,
        fromSchedule: true,
      };

      const calc = calculatePayroll(input);

      // ✅ Deterministic ID — duplicate impossible
      const docId     = `${emp.employeeNo}_${safeMonth}`;
      const newDocRef = doc(db, "restaurants", restaurantId, "payroll", docId);

      batch.set(newDocRef, {
        ...input,
        grossSalary: calc.grossSalary,
        taxAmount: calc.taxAmount,
        socialSecurityAmount: calc.socialSecurityAmount,
        netSalary: calc.netSalary,
        restaurantId,
        userId: auth.currentUser?.uid ?? "",
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      created++;
    });

    await batch.commit();
    batchIndex += BATCH_LIMIT;
  }

  return { created, skipped };
}

// ── Employee Master DB ────────────────────────
export async function getEmployees(
  restaurantId: string
): Promise<EmployeeRecord[]> {
  const snap = await getDocs(
    collection(db, "restaurants", restaurantId, "employees")
  );
  return snap.docs
    .map((d) => ({ id: d.id, ...(d.data() as Omit<EmployeeRecord, "id">) }))
    .filter((e) => e.active !== false)
    .sort((a, b) => a.employeeName.localeCompare(b.employeeName));
}

export async function getEmployee(
  restaurantId: string,
  employeeNo: string
): Promise<EmployeeRecord | null> {
  const snap = await getDocs(query(
    collection(db, "restaurants", restaurantId, "employees"),
    where("employeeNo", "==", employeeNo)
  ));
  if (snap.empty) return null;
  const d = snap.docs[0];
  return { id: d.id, ...(d.data() as Omit<EmployeeRecord, "id">) };
}
