// ============================================
// SERVORA ERP — Theme & Language System
// ✅ error field added to all themes
// ============================================

export type ThemeName = "navyDark" | "purpleDark" | "light";
export type LanguageCode = "en" | "np" | "pt" | "es" | "fr" | "ar" | "zh" | "hi" | "de" | "it";

export const THEMES: Record<ThemeName, {
  name: string;
  bg: string;
  surface: string;
  card: string;
  sidebar: string;
  sidebarText: string;
  sidebarActive: string;
  sidebarActiveText: string;
  sidebarSection: string;
  text: string;
  textSecondary: string;
  border: string;
  primary: string;
  accent: string;
  error: string;  // ✅ added
  navBg: string;
  navText: string;
}> = {
  navyDark: {
    name:              "Navy Dark",
    bg:                "#eef2f7",
    surface:           "#ffffff",
    card:              "#ffffff",
    sidebar:           "#00154f",
    sidebarText:       "rgba(255,255,255,0.8)",
    sidebarActive:     "rgba(255,215,0,0.15)",
    sidebarActiveText: "#FFD700",
    sidebarSection:    "rgba(255,255,255,0.3)",
    text:              "#1a1a2e",
    textSecondary:     "#64748b",
    border:            "rgba(255,255,255,0.1)",
    primary:           "#00154f",
    accent:            "#FFD700",
    error:             "#ef4444",  // ✅
    navBg:             "#00154f",
    navText:           "#ffffff",
  },
  purpleDark: {
    name:              "Purple Dark",
    bg:                "#0f0f1a",
    surface:           "#1a1a2e",
    card:              "#16213e",
    sidebar:           "#1a1a2e",
    sidebarText:       "rgba(255,255,255,0.75)",
    sidebarActive:     "rgba(124,58,237,0.25)",
    sidebarActiveText: "#a78bfa",
    sidebarSection:    "rgba(255,255,255,0.25)",
    text:              "#f1f5f9",
    textSecondary:     "#94a3b8",
    border:            "rgba(255,255,255,0.08)",
    primary:           "#7c3aed",
    accent:            "#a78bfa",
    error:             "#ef4444",  // ✅
    navBg:             "#1a1a2e",
    navText:           "#f1f5f9",
  },
  light: {
    name:              "Light",
    bg:                "#f8fafc",
    surface:           "#ffffff",
    card:              "#ffffff",
    sidebar:           "#1e293b",
    sidebarText:       "rgba(255,255,255,0.8)",
    sidebarActive:     "rgba(59,130,246,0.15)",
    sidebarActiveText: "#60a5fa",
    sidebarSection:    "rgba(255,255,255,0.3)",
    text:              "#0f172a",
    textSecondary:     "#64748b",
    border:            "#e2e8f0",
    primary:           "#1e40af",
    accent:            "#3b82f6",
    error:             "#ef4444",  // ✅
    navBg:             "#1e293b",
    navText:           "#ffffff",
  },
};

export const LANGUAGES: Record<LanguageCode, { name: string; flag: string; rtl: boolean }> = {
  en: { name: "English",    flag: "🇬🇧", rtl: false },
  np: { name: "नेपाली",      flag: "🇳🇵", rtl: false },
  pt: { name: "Português",  flag: "🇵🇹", rtl: false },
  es: { name: "Español",    flag: "🇪🇸", rtl: false },
  fr: { name: "Français",   flag: "🇫🇷", rtl: false },
  ar: { name: "العربية",    flag: "🇸🇦", rtl: true  },
  zh: { name: "中文",        flag: "🇨🇳", rtl: false },
  hi: { name: "हिन्दी",      flag: "🇮🇳", rtl: false },
  de: { name: "Deutsch",    flag: "🇩🇪", rtl: false },
  it: { name: "Italiano",   flag: "🇮🇹", rtl: false },
};

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appName: "SERVORA ERP",
    appSubtitle: "Restaurant Management System",
    dashboard: "Dashboard",
    salesEntry: "Sales Entry",
    salesList: "Sales List",
    expenses: "Expenses",
    inventory: "Inventory",
    billing: "Billing",
    kitchen: "Kitchen",
    reports: "Reports",
    payroll: "Payroll",
    profitLoss: "Profit & Loss",
    monthlyReport: "Monthly Report",
    employees: "Employees",
    suppliers: "Suppliers",
    customers: "Customers",
    purchaseOrders: "Purchase Orders",
    settings: "Settings",
    users: "Users",
    auditLog: "Audit Log",
    backup: "Backup",
    store: "Store",
    schedule: "Schedule",
    logout: "Logout",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    createAccount: "Create New Account",
    totalSales: "Total Sales",
    totalExpenses: "Total Expenses",
    netProfit: "Net Profit",
    management: "Management",
    operations: "Operations",
    finance: "Finance",
    system: "System",
    main: "Main",
    openApp: "Open App",
    welcomeBack: "Welcome Back",
    loginToContinue: "Login to continue",
    theme: "Theme",
    language: "Language",
    executiveDashboard: "Executive Dashboard",
    analytics: "Analytics",
    pos: "POS System",
    attendance: "Attendance",
    reservations: "Reservations",
    delivery: "Delivery",
    restaurants: "Restaurants",
    branches: "Branches",
  },
  np: {
    appName: "सर्भोरा ERP",
    appSubtitle: "रेस्टुरेन्ट व्यवस्थापन प्रणाली",
    dashboard: "ड्यासबोर्ड",
    salesEntry: "बिक्री प्रविष्टि",
    salesList: "बिक्री सूची",
    expenses: "खर्च",
    inventory: "सूची",
    billing: "बिलिङ",
    kitchen: "भान्सा",
    reports: "रिपोर्ट",
    payroll: "तलब",
    profitLoss: "नाफा र नोक्सान",
    monthlyReport: "मासिक रिपोर्ट",
    employees: "कर्मचारी",
    suppliers: "आपूर्तिकर्ता",
    customers: "ग्राहक",
    purchaseOrders: "खरिद अर्डर",
    settings: "सेटिङ",
    users: "प्रयोगकर्ता",
    auditLog: "लेखा परीक्षण",
    backup: "ब्याकअप",
    store: "स्टोर",
    schedule: "तालिका",
    logout: "बाहिर निस्कनुस्",
    login: "लगइन",
    register: "दर्ता गर्नुस्",
    email: "इमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भुल्नुभयो?",
    createAccount: "नयाँ खाता बनाउनुस्",
    totalSales: "कुल बिक्री",
    totalExpenses: "कुल खर्च",
    netProfit: "खुद नाफा",
    management: "व्यवस्थापन",
    operations: "सञ्चालन",
    finance: "वित्त",
    system: "प्रणाली",
    main: "मुख्य",
    openApp: "एप खोल्नुस्",
    welcomeBack: "स्वागत छ",
    loginToContinue: "जारी राख्न लगइन गर्नुस्",
    theme: "थिम",
    language: "भाषा",
    executiveDashboard: "कार्यकारी ड्यासबोर्ड",
    analytics: "विश्लेषण",
    pos: "POS प्रणाली",
    attendance: "उपस्थिति",
    reservations: "आरक्षण",
    delivery: "डेलिभरी",
    restaurants: "रेस्टुरेन्टहरू",
    branches: "शाखाहरू",
  },
  pt: {
    appName: "SERVORA ERP",
    appSubtitle: "Sistema de Gestão de Restaurante",
    dashboard: "Painel",
    salesEntry: "Entrada de Vendas",
    salesList: "Lista de Vendas",
    expenses: "Despesas",
    inventory: "Inventário",
    billing: "Faturação",
    kitchen: "Cozinha",
    reports: "Relatórios",
    payroll: "Folha de Pagamento",
    profitLoss: "Lucros e Perdas",
    monthlyReport: "Relatório Mensal",
    employees: "Funcionários",
    suppliers: "Fornecedores",
    customers: "Clientes",
    purchaseOrders: "Ordens de Compra",
    settings: "Configurações",
    users: "Utilizadores",
    auditLog: "Registo de Auditoria",
    backup: "Backup",
    store: "Armazém",
    schedule: "Horário",
    logout: "Sair",
    login: "Entrar",
    register: "Registar",
    email: "Email",
    password: "Palavra-passe",
    forgotPassword: "Esqueceu a senha?",
    createAccount: "Criar Nova Conta",
    totalSales: "Total de Vendas",
    totalExpenses: "Total de Despesas",
    netProfit: "Lucro Líquido",
    management: "Gestão",
    operations: "Operações",
    finance: "Finanças",
    system: "Sistema",
    main: "Principal",
    openApp: "Abrir App",
    welcomeBack: "Bem-vindo",
    loginToContinue: "Faça login para continuar",
    theme: "Tema",
    language: "Idioma",
    executiveDashboard: "Painel Executivo",
    analytics: "Análises",
    pos: "Sistema POS",
    attendance: "Presença",
    reservations: "Reservas",
    delivery: "Entrega",
    restaurants: "Restaurantes",
    branches: "Filiais",
  },
  es: {
    appName: "SERVORA ERP",
    appSubtitle: "Sistema de Gestión de Restaurante",
    dashboard: "Panel",
    salesEntry: "Entrada de Ventas",
    salesList: "Lista de Ventas",
    expenses: "Gastos",
    inventory: "Inventario",
    billing: "Facturación",
    kitchen: "Cocina",
    reports: "Informes",
    payroll: "Nómina",
    profitLoss: "Pérdidas y Ganancias",
    monthlyReport: "Informe Mensual",
    employees: "Empleados",
    suppliers: "Proveedores",
    customers: "Clientes",
    purchaseOrders: "Órdenes de Compra",
    settings: "Configuración",
    users: "Usuarios",
    auditLog: "Registro de Auditoría",
    backup: "Respaldo",
    store: "Almacén",
    schedule: "Horario",
    logout: "Cerrar Sesión",
    login: "Iniciar Sesión",
    register: "Registrarse",
    email: "Correo",
    password: "Contraseña",
    forgotPassword: "¿Olvidó su contraseña?",
    createAccount: "Crear Nueva Cuenta",
    totalSales: "Ventas Totales",
    totalExpenses: "Gastos Totales",
    netProfit: "Beneficio Neto",
    management: "Gestión",
    operations: "Operaciones",
    finance: "Finanzas",
    system: "Sistema",
    main: "Principal",
    openApp: "Abrir App",
    welcomeBack: "Bienvenido",
    loginToContinue: "Inicia sesión para continuar",
    theme: "Tema",
    language: "Idioma",
    executiveDashboard: "Panel Ejecutivo",
    analytics: "Análisis",
    pos: "Sistema POS",
    attendance: "Asistencia",
    reservations: "Reservas",
    delivery: "Entrega",
    restaurants: "Restaurantes",
    branches: "Sucursales",
  },
  fr: {
    appName: "SERVORA ERP",
    appSubtitle: "Système de Gestion de Restaurant",
    dashboard: "Tableau de Bord",
    salesEntry: "Saisie des Ventes",
    salesList: "Liste des Ventes",
    expenses: "Dépenses",
    inventory: "Inventaire",
    billing: "Facturation",
    kitchen: "Cuisine",
    reports: "Rapports",
    payroll: "Paie",
    profitLoss: "Profits et Pertes",
    monthlyReport: "Rapport Mensuel",
    employees: "Employés",
    suppliers: "Fournisseurs",
    customers: "Clients",
    purchaseOrders: "Bons de Commande",
    settings: "Paramètres",
    users: "Utilisateurs",
    auditLog: "Journal d'Audit",
    backup: "Sauvegarde",
    store: "Magasin",
    schedule: "Horaire",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    email: "Email",
    password: "Mot de Passe",
    forgotPassword: "Mot de passe oublié?",
    createAccount: "Créer un Compte",
    totalSales: "Ventes Totales",
    totalExpenses: "Dépenses Totales",
    netProfit: "Bénéfice Net",
    management: "Gestion",
    operations: "Opérations",
    finance: "Finance",
    system: "Système",
    main: "Principal",
    openApp: "Ouvrir l'App",
    welcomeBack: "Bienvenue",
    loginToContinue: "Connectez-vous pour continuer",
    theme: "Thème",
    language: "Langue",
    executiveDashboard: "Tableau Exécutif",
    analytics: "Analytique",
    pos: "Système POS",
    attendance: "Présence",
    reservations: "Réservations",
    delivery: "Livraison",
    restaurants: "Restaurants",
    branches: "Succursales",
  },
  ar: {
    appName: "سيرفورا ERP",
    appSubtitle: "نظام إدارة المطاعم",
    dashboard: "لوحة التحكم",
    salesEntry: "إدخال المبيعات",
    salesList: "قائمة المبيعات",
    expenses: "المصروفات",
    inventory: "المخزون",
    billing: "الفواتير",
    kitchen: "المطبخ",
    reports: "التقارير",
    payroll: "الرواتب",
    profitLoss: "الأرباح والخسائر",
    monthlyReport: "التقرير الشهري",
    employees: "الموظفون",
    suppliers: "الموردون",
    customers: "العملاء",
    purchaseOrders: "أوامر الشراء",
    settings: "الإعدادات",
    users: "المستخدمون",
    auditLog: "سجل المراجعة",
    backup: "نسخ احتياطي",
    store: "المخزن",
    schedule: "الجدول",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    register: "تسجيل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    createAccount: "إنشاء حساب جديد",
    totalSales: "إجمالي المبيعات",
    totalExpenses: "إجمالي المصروفات",
    netProfit: "صافي الربح",
    management: "الإدارة",
    operations: "العمليات",
    finance: "المالية",
    system: "النظام",
    main: "الرئيسية",
    openApp: "فتح التطبيق",
    welcomeBack: "مرحباً بعودتك",
    loginToContinue: "سجل دخولك للمتابعة",
    theme: "المظهر",
    language: "اللغة",
    executiveDashboard: "لوحة تحكم تنفيذية",
    analytics: "التحليلات",
    pos: "نظام نقاط البيع",
    attendance: "الحضور",
    reservations: "الحجوزات",
    delivery: "التوصيل",
    restaurants: "المطاعم",
    branches: "الفروع",
  },
  zh: {
    appName: "SERVORA ERP",
    appSubtitle: "餐厅管理系统",
    dashboard: "仪表板",
    salesEntry: "销售录入",
    salesList: "销售列表",
    expenses: "费用",
    inventory: "库存",
    billing: "账单",
    kitchen: "厨房",
    reports: "报告",
    payroll: "薪资",
    profitLoss: "损益",
    monthlyReport: "月度报告",
    employees: "员工",
    suppliers: "供应商",
    customers: "客户",
    purchaseOrders: "采购订单",
    settings: "设置",
    users: "用户",
    auditLog: "审计日志",
    backup: "备份",
    store: "仓库",
    schedule: "时间表",
    logout: "退出",
    login: "登录",
    register: "注册",
    email: "邮箱",
    password: "密码",
    forgotPassword: "忘记密码？",
    createAccount: "创建新账户",
    totalSales: "总销售额",
    totalExpenses: "总费用",
    netProfit: "净利润",
    management: "管理",
    operations: "运营",
    finance: "财务",
    system: "系统",
    main: "主要",
    openApp: "打开应用",
    welcomeBack: "欢迎回来",
    loginToContinue: "请登录继续",
    theme: "主题",
    language: "语言",
    executiveDashboard: "执行仪表板",
    analytics: "分析",
    pos: "POS系统",
    attendance: "考勤",
    reservations: "预订",
    delivery: "配送",
    restaurants: "餐厅",
    branches: "分店",
  },
  hi: {
    appName: "सर्वोरा ERP",
    appSubtitle: "रेस्तरां प्रबंधन प्रणाली",
    dashboard: "डैशबोर्ड",
    salesEntry: "बिक्री प्रविष्टि",
    salesList: "बिक्री सूची",
    expenses: "खर्च",
    inventory: "सूची",
    billing: "बिलिंग",
    kitchen: "रसोई",
    reports: "रिपोर्ट",
    payroll: "वेतन",
    profitLoss: "लाभ और हानि",
    monthlyReport: "मासिक रिपोर्ट",
    employees: "कर्मचारी",
    suppliers: "आपूर्तिकर्ता",
    customers: "ग्राहक",
    purchaseOrders: "खरीद आदेश",
    settings: "सेटिंग्स",
    users: "उपयोगकर्ता",
    auditLog: "ऑडिट लॉग",
    backup: "बैकअप",
    store: "स्टोर",
    schedule: "अनुसूची",
    logout: "लॉग आउट",
    login: "लॉग इन",
    register: "पंजीकरण",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    createAccount: "नया खाता बनाएं",
    totalSales: "कुल बिक्री",
    totalExpenses: "कुल खर्च",
    netProfit: "शुद्ध लाभ",
    management: "प्रबंधन",
    operations: "संचालन",
    finance: "वित्त",
    system: "प्रणाली",
    main: "मुख्य",
    openApp: "ऐप खोलें",
    welcomeBack: "वापस स्वागत है",
    loginToContinue: "जारी रखने के लिए लॉगिन करें",
    theme: "थीम",
    language: "भाषा",
    executiveDashboard: "कार्यकारी डैशबोर्ड",
    analytics: "विश्लेषण",
    pos: "POS प्रणाली",
    attendance: "उपस्थिति",
    reservations: "आरक्षण",
    delivery: "डिलीवरी",
    restaurants: "रेस्तरां",
    branches: "शाखाएं",
  },
  de: {
    appName: "SERVORA ERP",
    appSubtitle: "Restaurantmanagementsystem",
    dashboard: "Dashboard",
    salesEntry: "Verkaufseingabe",
    salesList: "Verkaufsliste",
    expenses: "Ausgaben",
    inventory: "Inventar",
    billing: "Abrechnung",
    kitchen: "Küche",
    reports: "Berichte",
    payroll: "Gehaltsabrechnung",
    profitLoss: "Gewinn und Verlust",
    monthlyReport: "Monatsbericht",
    employees: "Mitarbeiter",
    suppliers: "Lieferanten",
    customers: "Kunden",
    purchaseOrders: "Bestellungen",
    settings: "Einstellungen",
    users: "Benutzer",
    auditLog: "Prüfprotokoll",
    backup: "Sicherung",
    store: "Lager",
    schedule: "Zeitplan",
    logout: "Abmelden",
    login: "Anmelden",
    register: "Registrieren",
    email: "E-Mail",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    createAccount: "Neues Konto erstellen",
    totalSales: "Gesamtumsatz",
    totalExpenses: "Gesamtausgaben",
    netProfit: "Nettogewinn",
    management: "Verwaltung",
    operations: "Betrieb",
    finance: "Finanzen",
    system: "System",
    main: "Haupt",
    openApp: "App öffnen",
    welcomeBack: "Willkommen zurück",
    loginToContinue: "Melden Sie sich an, um fortzufahren",
    theme: "Thema",
    language: "Sprache",
    executiveDashboard: "Executive Dashboard",
    analytics: "Analytik",
    pos: "POS-System",
    attendance: "Anwesenheit",
    reservations: "Reservierungen",
    delivery: "Lieferung",
    restaurants: "Restaurants",
    branches: "Filialen",
  },
  it: {
    appName: "SERVORA ERP",
    appSubtitle: "Sistema di Gestione Ristorante",
    dashboard: "Pannello",
    salesEntry: "Inserimento Vendite",
    salesList: "Lista Vendite",
    expenses: "Spese",
    inventory: "Inventario",
    billing: "Fatturazione",
    kitchen: "Cucina",
    reports: "Rapporti",
    payroll: "Stipendi",
    profitLoss: "Profitti e Perdite",
    monthlyReport: "Rapporto Mensile",
    employees: "Dipendenti",
    suppliers: "Fornitori",
    customers: "Clienti",
    purchaseOrders: "Ordini di Acquisto",
    settings: "Impostazioni",
    users: "Utenti",
    auditLog: "Registro Audit",
    backup: "Backup",
    store: "Magazzino",
    schedule: "Orario",
    logout: "Esci",
    login: "Accedi",
    register: "Registrati",
    email: "Email",
    password: "Password",
    forgotPassword: "Password dimenticata?",
    createAccount: "Crea Nuovo Account",
    totalSales: "Vendite Totali",
    totalExpenses: "Spese Totali",
    netProfit: "Utile Netto",
    management: "Gestione",
    operations: "Operazioni",
    finance: "Finanza",
    system: "Sistema",
    main: "Principale",
    openApp: "Apri App",
    welcomeBack: "Bentornato",
    loginToContinue: "Accedi per continuare",
    theme: "Tema",
    language: "Lingua",
    executiveDashboard: "Dashboard Esecutivo",
    analytics: "Analisi",
    pos: "Sistema POS",
    attendance: "Presenze",
    reservations: "Prenotazioni",
    delivery: "Consegna",
    restaurants: "Ristoranti",
    branches: "Filiali",
  },
};