// ============================================
// SERVORA ERP — Payroll Generator v3
// ✅ No getDoc inside loop — faster
// ✅ createdAt = serverTimestamp() only
// ✅ restaurantPayrollDays from attendance
// ✅ employeeMap one-time load
// ✅ batch writes
// ============================================

import {
  collection, doc, getDocs,
  query, where, writeBatch, serverTimestamp,
} from "firebase/firestore";
import { db, auth } from "../../firebase";
import { getMonthlyAttendance } from "./utils/payroll-attendance";
import { resolveSnapshot } from "./utils/payroll-snapshot";
import { calculatePayroll } from "./utils/payroll-calculator";
import {
  getExistingPayrollNos,
  buildPayrollId,
} from "./firestore/payroll-repository";
import { PayrollDocument, PayrollStatus } from "./types/payroll-types";
import { SCHEDULE_CONFIG } from "../schedule-module/constants/schedule-config";

async function loadEmployeeMap(
  restaurantId: string,
  employeeNos: string[]
): Promise<Record<string, any>> {
  const map: Record<string, any> = {};
  if (employeeNos.length === 0) return map;

  const CHUNK = SCHEDULE_CONFIG.FIRESTORE_IN_QUERY_LIMIT;
  for (let i = 0; i < employeeNos.length; i += CHUNK) {
    const chunk = employeeNos.slice(i, i + CHUNK);
    const snap  = await getDocs(query(
      collection(db, "restaurants", restaurantId, "employees"),
      where("employeeNo", "in", chunk)
    ));
    snap.docs.forEach((d) => {
      const data = d.data();
      map[data.employeeNo] = data;
    });
  }
  return map;
}

export async function generateMonthlyPayroll(
  restaurantId: string,
  year: number,
  month: number,
  monthStr: string
): Promise<{ created: number; skipped: number }> {

  // ── Step 1: Attendance ────────────────────
  const attendance = await getMonthlyAttendance(restaurantId, year, month);
  if (attendance.length === 0) return { created: 0, skipped: 0 };

  // ── Step 2: Filter existing ───────────────
  const existingNos = await getExistingPayrollNos(restaurantId, monthStr);
  const toCreate    = attendance.filter((e) => !existingNos.has(e.employeeNo));
  const skipped     = attendance.length - toCreate.length;
  if (toCreate.length === 0) return { created: 0, skipped };

  // ── Step 3: Load employeeMap ONCE ─────────
  const noSnapshot  = toCreate.filter((e) => !e.employeeSnapshot);
  const employeeMap = await loadEmployeeMap(
    restaurantId,
    noSnapshot.map((e) => e.employeeNo)
  );

  // ── Step 4: Batch write ───────────────────
  const LIMIT = SCHEDULE_CONFIG.BATCH_WRITE_LIMIT;
  let created = 0;

  for (let i = 0; i < toCreate.length; i += LIMIT) {
    const chunk = toCreate.slice(i, i + LIMIT);
    const batch = writeBatch(db);

    chunk.forEach((emp) => {
      const snapshot = resolveSnapshot(
        emp.employeeNo,
        emp.employeeSnapshot,
        employeeMap
      );
      if (!snapshot) return;

      // ✅ restaurantPayrollDays from MonthlyAttendance
      const totalDays = emp.restaurantPayrollDays ?? 30;

      const calc = calculatePayroll(
        snapshot,
        {
          workingDays:   emp.workingDays,
          totalDays,
          overtimeHours: emp.overtimeHours,
          nightHours:    emp.nightHours,
          holidayHours:  emp.holidayHours,
        },
        emp.allowances ?? [],
        0
      );

      const docId  = buildPayrollId(emp.employeeNo, monthStr);
      const docRef = doc(
        collection(db, "restaurants", restaurantId, "payroll"),
        docId
      );

      const payrollData: Omit<PayrollDocument, "id"> = {
        employeeNo:   emp.employeeNo,
        employeeName: emp.employeeName,
        position:     emp.position,
        month:        monthStr,
        snapshot,
        attendance: {
          workingDays:   emp.workingDays,
          totalHours:    emp.totalHours,
          overtimeHours: emp.overtimeHours,
          nightHours:    emp.nightHours,
          holidayDays:   emp.holidayDays,
          holidayHours:  emp.holidayHours,
          absentDays:    emp.absentDays,
          sickDays:      emp.sickDays,
          vacationDays:  emp.vacationDays,
          trainingHours: emp.trainingHours,
        },
        allowances:      emp.allowances ?? [],
        calculation:     calc,
        otherDeductions: 0,
        payrollStatus:   "GENERATED" as PayrollStatus,
        locked:          true,
        autoGenerated:   true,
        fromSchedule:    true,
        restaurantId,
        userId:          auth.currentUser?.uid ?? "",
      };

      batch.set(docRef, {
        ...payrollData,
        // ✅ createdAt = serverTimestamp() only — no loop read needed
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      created++;
    });

    await batch.commit();
  }

  return { created, skipped };
}