// ============================================
// SERVORA ERP — Supplier Types
// ✅ No duplicate-name enforcement (unlike Category/Department) —
//    real-world suppliers can legitimately share similar/same names
//    (different branches, different people with the same business
//    name), so this is intentionally NOT blocked at the repository
//    layer. A soft "similar name exists" warning belongs in the UI
//    layer (Phase 8), not a hard rejection here.
// ✅ EXTENDED (Phase 8.3) — companyName, taxId, country, currency,
//    paymentTerms, status added as OPTIONAL fields (status defaults
//    to ACTIVE) so existing suppliers keep working unchanged.
//    supplierCode is auto-generated by the repository at creation,
//    same pattern as PurchaseOrder.poNumber — never client-supplied,
//    never editable after creation.
// ✅ taxId (not vatNumber) — generic name covers VAT (Europe), GST
//    (India), EIN (US), ABN (Australia) etc. under one field; the
//    UI shows it as "VAT / Tax Number" so it reads naturally for
//    both Europe-based and non-Europe users without needing a
//    separate field per country's tax-ID naming convention.
// FROZEN
// ============================================

export type SupplierStatus = "ACTIVE" | "INACTIVE";

export interface Supplier {
  id:             string;
  supplierCode:   string;  // auto-generated, e.g. "SUP-0001" — never client-supplied
  name:           string;
  companyName?:   string;
  contactPerson?: string;
  phone?:         string;
  email?:         string;
  taxId?:         string;  // VAT / GST / EIN / ABN — shown as "VAT / Tax Number" in UI
  address?:       string;
  country?:       string;
  currency?:      string;  // ISO code, e.g. "EUR", "USD", "GBP", "NPR"
  paymentTerms?:  string;  // free text, e.g. "Net 30", "COD", "Advance"
  status:         SupplierStatus;
  notes?:         string;
  restaurantId:   string;
  createdAt?:     unknown;
  updatedAt?:     unknown;
}

export interface CreateSupplierInput {
  name:           string;
  companyName?:   string;
  contactPerson?: string;
  phone?:         string;
  email?:         string;
  taxId?:         string;
  address?:       string;
  country?:       string;
  currency?:      string;
  paymentTerms?:  string;
  status?:        SupplierStatus;  // defaults to "ACTIVE" if omitted
  notes?:         string;
}

export type UpdateSupplierInput = Partial<CreateSupplierInput>;