import * as Print from "expo-print";

import * as Sharing from "expo-sharing";

export async function exportPDF(

  title: string,

  companyName: string,

  content: string

) {

  try {

    const html = `

    <html>

      <head>

        <style>

          body {

            font-family: Arial;

            padding: 30px;

          }

          h1 {

            color: #00154f;

          }

          h2 {

            color: #0039cb;

          }

          .company {

            font-size: 24px;

            font-weight: bold;

            margin-bottom: 10px;

          }

          .report {

            margin-top: 20px;

          }

          .footer {

            margin-top: 40px;

            font-size: 12px;

            color: gray;

          }

        </style>

      </head>

      <body>

        <div class="company">

          ${companyName}

        </div>

        <h1>

          SERVORA ERP

        </h1>

        <h2>

          ${title}

        </h2>

        <hr />

        <div class="report">

          ${content}

        </div>

        <div class="footer">

          Generated by SERVORA ERP

          <br/>

          ${new Date().toLocaleString()}

        </div>

      </body>

    </html>

    `;

    const file =

      await Print.printToFileAsync({

        html,

      });

    const available =

      await Sharing.isAvailableAsync();

    if (available) {

      await Sharing.shareAsync(

        file.uri

      );

    }

  } catch (error) {

    console.log(

      "PDF Export Error:",

      error

    );

  }

}